#Database Settings
spring:
  application:
    name: Query Market Place
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc.batch_size: 1000
      hibernate.cache:
        use_query_cache: false
        use_second_level_cache: false
        use_structured_entries: false
        use_minimal_puts: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://172.28.128.1:5432/query-marketplace
    username: postgres
    password: Mikaza146#
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      default-auto-commit: true

#Server settings
server:
  servlet:
    context-path: /marketplace
    display-name: <a href='/safari'>Query Marketplace API</a>

openapi:
  queryMarketplace:
    base-path: /marketplace