openapi: 3.0.3
info:
#  description: Query Marketplace
  version: "1.0.0"
  title: Query Marketplace
  contact:
    name: Walter de Sola
    email: waldesro@gmail.com
servers:
  - url: 'http://{environment}.junglesoftware.com'
    description: Non-Production
    variables:
      environment:
        default: int
        enum:
          - int
          - uat
  - url: 'https://junglesoftware.com'
    description: Production
security:
  - OAuth2:
      - query-marketplace:read
      - query-Marketplace:write
paths:
  /account/v1/createAccount:
    post:
      tags:
        - createAccount
      summary: Create Account
      security:
        - OAuth2:
            - query-Marketplace:write
      operationId: createAccount
      description: Create Account with required data
      responses:
        200:
          $ref: '#/components/responses/200-AccountCreated'
        402:
          $ref: '#/components/responses/402-AccountExists'
        405:
          $ref: '#/components/responses/405-InvalidAccountInfo'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInfoRequest'
  /query/v1/listAll/{softwareId}:
    parameters:
      - $ref: '#/components/parameters/SoftwareId'
    get:
      tags:
        - ListAllQueries
      summary: Return list of queries available for the software
      security:
        - OAuth2:
            - query-marketplace:read
      description: Return a list with all queries for a given software
      operationId: listAllQueries
      responses:
        200:
          $ref: '#/components/responses/200-ListAllQueries'
        404:
          $ref: '#/components/responses/404-ApplicationNotFound'
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: This API uses OAuth 2 with the explicit grant flow
      flows:
        authorizationCode:
          tokenUrl: http://localhost:8080
          authorizationUrl: http://localhost:8080
          scopes:
            query-marketplace:read: Read operation
            query-Marketplace:write: Write operation
  parameters:
    SoftwareId:
      name: softwareId
      in: path
      description: Software Id
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    ErrorsDTO:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDTO'
    ErrorDTO:
      type: object
      description: A single error in the API response
      required:
        - code
        - errorMessage
        - severity
      properties:
        code:
          type: string
          description: A unique ID for the particular error
          example: QMP-A-0001
        errorMessage:
          type: string
          description: Error detail
          example: Message example for UI feedback
        severity:
          type: string
          description: The severity of the error
          enum:
            - INFO
            - WARNING
            - ERROR
          example: ERROR
    QueryDetailsDTO:
      type: object
      description: List of query detail
      properties:
        queries:
          type: array
          items:
            $ref: '#/components/schemas/QueryDetailDTO'
    QueryDetailDTO:
      type: object
      description: Query detail
      required:
        - id
        - shortDescription
      properties:
        id:
          type: string
          format: uuid
          description: Query UUID
        shortDescription:
          type: string
          description: A short description about the query
          example: Account balance
        longDescription:
          type: string
          description: Long description
          example: This query provides detail of each account and the balance
        price: 
          type: number
          description: Query price in USA dollars
          example: 1.99
          format: double
        purchased:
          type: boolean
          description: Boolean indicating if the query was already purchased by the account
          example: true
        author:
          $ref: '#/components/schemas/AuthorDTO'
    AuthorDTO:
      type: object
      description: Query Author
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          description: Author Id
        name:
          type: string
          description: Author name
        photo: 
          type: string
          description: Path to photo
        detail:
          type: string
          description: Detail information about author
        profileLink:
          type: string
          description: Link to author profile
        numberOfQueries:
          type: integer
          description: Number of queries that author has
        overallReviewRate:
          type: number
          format: float
          description: Rate author has based on users reviews
          example: 4.5
        reviews:
          type: array
          description: List of reviews
          items:
            $ref: '#/components/schemas/AuthorReviewDTO'
    AuthorReviewDTO:
      type: object
      description: Author review
      required:
        - id
        - reviewComment
        - rate
        - date
      properties:
        id:
          type: string
          format: uuid
          description: Review Id
        reviewComment:
          type: string
          description: Review comments
        rate:
          type: number
          description: Rate
          format: float
          example: 4.5
        date:
          type: string
          format: date-time
          description: Date and Time of review
    AccountInfoRequest:
      type: object
      properties:
        accountInfo:
          $ref: '#/components/schemas/AccountInfoDTO'
    AccountInfoDTO:
      type: object
      description: Information about the account
      required:
        - user
        - password
        - name
        - softwareId
        - countryISO
      properties:
        user:
          type: string
          format: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
          description: User email
        password:
          type: string
          format: password
          description: User password
        name:
          type: string
          description: Full name
        softwareId:
          type: string
          format: uuid
          description: Software used for ERP
        countryISO:
          type: string
          description: Country ISO3 code
          maxLength: 3
          minLength: 3
          example: USA
  responses:
    200-AccountCreated:
      description: Account was successfully created
    200-ListAllQueries:
      description: List of all queries
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/QueryDetailsDTO'
    405-InvalidAccountInfo:
      description: Invalid account information
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsDTO'
    402-AccountExists:
      description: Account could not be created. Existing one
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsDTO'
    404-ApplicationNotFound:
      description: Application ID not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorsDTO'
    400-BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
    401-Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDTO'
